/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

module.exports = {
  homeProjectSidebar: [
    {
      type: 'autogenerated',
      dirName: 'home-projects', // name of the folder under /docs
    },
  ],
  onJobProjectSidebar: [
    {
      type: 'autogenerated',
      dirName: 'on-job-projects', // name of the folder under /docs
    },
  ],
};
